#' @title select_metric for the server
#' 
#' @description selects the metric for which values are to generated and outputted to the graph. eg - deaths, confirmed, tests, recovered
#' 
#' @import shiny
#' 
#' @param filtered_data filtered dataset from user input countries and date range
#' @param input reactivevalues object generated by shiny input functions in the UI part
#'    
#' @export
select_metric <- function(filtered_data, input) {
  selected_metric <<- reactive({
    data <- filtered_data()
    data %>%
      rename(metric = input$metric)
  })
}

"select_metric"